from setuptools import setup, find_packages

setup(
    name="sdxl-webui",
    version="1.0.0",
    description="Modern Flask-based web interface for Stable Diffusion XL",
    author="DrxmReal",
    author_email="example@example.com",
    url="https://github.com/DrxmReal/sdxl-webui-flask",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "flask>=2.0.0",
        "torch>=2.0.0",
        "numpy>=1.20.0",
        "pillow>=9.0.0",
        "diffusers>=0.18.0",
        "transformers>=4.30.0",
        "accelerate>=0.20.0",
        "werkzeug>=2.0.0",
        "requests>=2.25.0",
        "pyngrok>=5.0.0",
        "basicsr<1.4.2",
        "realesrgan>=0.3.0",
        "opencv-python>=4.5.0",
        "scipy>=1.7.0",
        "ftfy>=6.0.0",
        "huggingface-hub>=0.14.0",
        "controlnet-aux>=0.0.3",
        "omegaconf>=2.0.0",
        "tqdm>=4.64.0"
    ],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    python_requires=">=3.8",
) 